spring.application.name=notification-service

server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5432/supplysync_tenants
spring.datasource.username=postgres
spring.datasource.password=1805
spring.datasource.driver-class-name=org.postgresql.Driver

# notifications table lives in public schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false
