spring.application.name=order-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/supplysync_tenants
spring.datasource.username=postgres
spring.datasource.password=1805
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false

# Kafka producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
