spring.application.name=auth-service


#PORT
server.port=8082

#PsSql Setup
spring.datasource.url=jdbc:postgresql://localhost:5432/supplysync_auth

spring.datasource.username=postgres
spring.datasource.password=1805

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false



# JWT config
jwt.secret=my-super-secret-key-that-should-be-at-least-256-bits-long-for-hs256-algorithm
jwt.expiration=86400000
# 86400000ms = 24 hours
