spring.application.name=product-service

server.port=8083

# PostgreSQL — same DB as tenant-service, schemas provide isolation
spring.datasource.url=jdbc:postgresql://localhost:5432/supplysync_tenants
spring.datasource.username=postgres
spring.datasource.password=1805
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate — ddl-auto=none because tenant-service creates tables per schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false
