spring.application.name=tenant-service

#PORT
server.port=8081

#PsSql Setup
spring.datasource.url=jdbc:postgresql://localhost:5432/supplysync_tenants
spring.datasource.username=postgres
spring.datasource.password=1805

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


